services:
  api_server:
    build: .
    image: api_server
    container_name: api_server
    hostname: api_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - cache_data:/data

volumes:
  mysql_data:
  cache_data: